#!/bin/bash
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0.01
mkdir 0.01
cp -rf 0.org/* 0.01

rm -rf bodiesInfo
mkdir bodiesInfo
cp -rf bodiesInfo.org/0.01 bodiesInfo/

runApplication blockMesh

application=`getApplication`
runApplication $application

paraFoam -touch

